language: node_js
node_js:
  - "7"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run build

after_script:
  - git remote show origin
  - cd ./example-dist
  - git init
  - git remote add origin "https://${GH_TOKEN}@${GH_REF}"
  - git remote show origin
  - git checkout -b gh-pages
  - git pull origin gh-pages
  - git branch
  - git config user.name "leezng"
  - git config user.email "leezng@163.com"
  - git add .
  - git commit -m "update example page"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

branches:
  only:
    - dev

env:
  global:
    - GH_REF: github.com/leezng/vue-json-pretty.git
